import 'package:hive_flutter/hive_flutter.dart';
import '../models/file_model.dart';
import '../models/version_model.dart';
import '../models/comment_model.dart';

// Box names — think of these like "table names" in SQL
const String kFileBox = 'files';
const String kVersionBox = 'versions';
const String kCommentBox = 'comments';

class HiveService {
  
  // Called once at app startup in main.dart
  static Future<void> init() async {
    await Hive.initFlutter(); // Sets up Hive in Flutter environment

    // Register TypeAdapters (auto-generated by build_runner)
    Hive.registerAdapter(FileModelAdapter());
    Hive.registerAdapter(VersionModelAdapter());
    Hive.registerAdapter(CommentModelAdapter());

    // Open the "tables"
    await Hive.openBox<FileModel>(kFileBox);
    await Hive.openBox<VersionModel>(kVersionBox);
    await Hive.openBox<CommentModel>(kCommentBox);
  }

  // Getters — access the open boxes anywhere in the app
  static Box<FileModel> get fileBox => Hive.box<FileModel>(kFileBox);
  static Box<VersionModel> get versionBox => Hive.box<VersionModel>(kVersionBox);
  static Box<CommentModel> get commentBox => Hive.box<CommentModel>(kCommentBox);
}