import 'package:hive/hive.dart';

part 'file_model.g.dart'; // Generated by build_runner

// HiveType gives this class a unique typeId (0) in Hive database
@HiveType(typeId: 0)
class FileModel extends HiveObject {
  
  @HiveField(0)
  final String id;           // Unique identifier

  @HiveField(1)
  String fileName;           // e.g. "Assignment_1.pdf"

  @HiveField(2)
  String fileType;           // e.g. "PDF", "DOCX", "IMAGE"

  @HiveField(3)
  String description;        // User-written description

  @HiveField(4)
  DateTime createdAt;        // When file was first added

  @HiveField(5)
  DateTime updatedAt;        // Last modification time

  @HiveField(6)
  bool isShared;             // true = visible in Shared Files screen

  @HiveField(7)
  bool isSynced;             // true = successfully pushed to backend

  @HiveField(8)
  int currentVersion;        // Latest version number

  @HiveField(9)
  String owner;              // Username/device that created file

  FileModel({
    required this.id,
    required this.fileName,
    required this.fileType,
    required this.description,
    required this.createdAt,
    required this.updatedAt,
    this.isShared = false,
    this.isSynced = false,
    this.currentVersion = 1,
    this.owner = 'Me',
  });

  // Creates a copy with updated fields (immutability pattern)
  FileModel copyWith({
    String? fileName,
    String? fileType,
    String? description,
    DateTime? updatedAt,
    bool? isShared,
    bool? isSynced,
    int? currentVersion,
  }) {
    return FileModel(
      id: id,
      fileName: fileName ?? this.fileName,
      fileType: fileType ?? this.fileType,
      description: description ?? this.description,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isShared: isShared ?? this.isShared,
      isSynced: isSynced ?? this.isSynced,
      currentVersion: currentVersion ?? this.currentVersion,
      owner: owner,
    );
  }

  // Convert to Map for API/JSON sync
  Map<String, dynamic> toMap() => {
    'id': id,
    'fileName': fileName,
    'fileType': fileType,
    'description': description,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'isShared': isShared,
    'isSynced': isSynced,
    'currentVersion': currentVersion,
    'owner': owner,
  };
}